services:
  web:
    build:
      context: ./ninjareact
    command: uvicorn ninjareact.asgi:application --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    restart: always
    volumes:
      - react:/app/frontend/dist
      - static:/app/static

  nginx:
    image: nginx
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - react:/app/frontend/dist:rw
      - static:/app/static:rw

volumes:
  react:
  static:

