services:
  web:
    build:
      context: ./ninjareact
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000 & npm run --prefix=frontend dev -- --host"
    env_file:
      - .env
    ports:
      - "5173:5173"
    restart: always
    volumes:
      - ./ninjareact:/app
      - /app/frontend/node_modules

