
services:
  backend:
    build:
      context: ./ninjareact
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
